/opt/chef/embedded/bin/ruby -I/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/rspec-support-3.1.2/lib:/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/localhost/\*_spec.rb

Package "git"
	should be installed

Package "httpd"
	should be installed

Package "jenkins"
	should be installed

Package "bundler"
	should be installed

Package "chef"
	should be installed