---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 11899, host: 4567 }]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[kitchen-docs::default]
    attributes:
