---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb
  customize:
        natdnshostresolver1: "on"

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: centos-6.5
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: volume-groups
    run_list:
        - recipe[volume-groups::default]
    attributes:
