name             'volume-groups'
maintainer       'Dave Tashner'
maintainer_email 'dtashner@singlestoneconsulting.com'
license          'All rights reserved'
description      'Creates volume groups for mounting filesystems'
long_description 'I needed this functionality for local testing with Test Kitchen; we are not yet using the kitchen-ec2 driver to spin up AMIs containing company-specific filesystems, so we needed a way to create new volume groups on blank CentOS boxes.'
version          '0.1.0'
